### ISSUE TITLE
Naming conflict

### ISSUE THREAD

**Issue by joukewitteveen** [akpoff/netctl#1]
For the last 5 years I have been maintaining a network manager that integrates with `systemd` under the name [netctl](https://github.com/joukewitteveen/netctl/). It even predates systemd's own `networkctl`!

Not that I mind, but you may want to consider renaming your project to avoid confusion when it becomes popular.

**Comment by akpoff** [comment]
Hi Jouke,
This `netctl` is OpenBSD specific...popular will be a limited audience.

In theory, it could be ported to Linux, but the amount of work required would outweighs the benefit and there's zero chance systemd will be
ported to OpenBSD.

Given the different audiences, the risk of confusion seems low.
