### ISSUE TITLE
use hardlinks instead of symlinks?

### ISSUE THREAD

**Issue by job** [akpoff/netctl#5]
Would it perhaps make sense to use hardlinks instead of symlinks to make upgrading easier? 

When I upgrade openbsd and the target filesystem is mounted on /mnt - the symlinks are dangling and I need to drop to shell to get my network interfaces up

**Comment by akpoff** [comment]
I ran into the same issue. I need the symbolic links to make the listing feature work, or at least to make my life easier. ;-)

 I've re-coded it to use relative links.

When you have a moment, will you try the latest release.
